name: Dev Testing

on:
  push:
  workflow_dispatch:

jobs:
  generate-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Code Coverage XML
        uses: ./.github/actions/generate-code-coverage
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
