# Copyright 2020-2023 The MathWorks, Inc

# Workflow that contains jobs to test MATLAB Proxy
name: Testing MATLAB Proxy Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  # Runs unit tests
  call-run-unit-tests-r000:
    uses: ./.github/workflows/run-unit-tests.yml

  call-run-unit-tests-r001:
    uses: ./.github/workflows/run-unit-tests.yml

  call-run-unit-tests-r002:
      uses: ./.github/workflows/run-unit-tests.yml

  generate-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Code Coverage XML
        uses: ./.github/actions/generate-code-coverage
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  # Runs integration tests
  call-integration-tests:
    uses: ./.github/workflows/run-integration-tests.yml
    secrets: inherit
